FROM node:24.1.0-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy the rest of the frontend code
COPY . ./

# Expose port for development server
EXPOSE 3000

# Start development server with hot reloading
CMD ["npm", "start"]
