version: "3.9"

services:
  backend:
    build: ./backend
    #image: talehopper-backend:dev
    container_name: talehopper-backend-dev
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:delegated
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    networks:
      - talehopper-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: talehopper-frontend:dev
    container_name: talehopper-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - talehopper-network

networks:
  talehopper-network:
    driver: bridge
