version: "3.9"

services:
  backend:
    build: ./backend
    #image: talehopper-backend:prod
    container_name: talehopper-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:ro
      - ./backend/tests:/app/tests:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - talehopper-network

  frontend:
    build: ./frontend
    image: talehopper-frontend:prod
    container_name: talehopper-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - talehopper-network

networks:
  talehopper-network:
    driver: bridge
